### ISSUE TITLE
Not able to enter budget value

### ISSUE THREAD

**Issue by bergziege** [linuxserver/budge#27]
Hi, I am running 0.0.8 via Docker and I am not be able to enter a value into the "Budgeted" column of my envelope. It always reverts back to 0.

- Click a field in the "budgeted" column
- Changes to an input field with "0"
- Typing "50" + ENTER
- Changes back to normal text and showing "0"

Settings changed from default: Currency set to EUR
Browser: Edge and Firefox
Running via Docker:

```
version: "2.1"
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    ports:
      - 7080:80
      - 7443:443
    restart: unless-stopped
```

**Comment by alex-phillips** [comment]
Can you share your docker logs after this issue occurs?

**Comment by bergziege** [comment]
> Can you share your docker logs after this issue occurs?

Those are the same as in #28 minus the transaction message ;-)
So no, there are no errors in the logs when trying to enter a value. But I can confirm I too get the logged in error, but not in a timely manner that would correlate with any budged entering actions.

**Comment by alex-phillips** [comment]
Could either of you share the console logs from the browser? Unless there is another error in the docker logs, this may be a UI / client-side error.

**Comment by bergziege** [comment]
Well, maybe we are onto something.

- set month to August
- clear log
- click in "Rent" - "Budgeted"
- enter "50"
- press Enter

![image](https://user-images.githubusercontent.com/354288/172683879-ce5757c9-a69a-4600-b5b5-cdace714d8aa.png)

**Comment by bergziege** [comment]
One strange thing I just discovered is that the budge container is using 20%-30% CPU load ... when doing nothing (at least nothing I can think of).

![image](https://user-images.githubusercontent.com/354288/172685944-ca6a8fc3-2ae8-4bbe-8c46-9d822a1feed0.png)

**Comment by alex-phillips** [comment]
What happens when you just go to the URL `http://192.168.1.105:7080/api/ping`? Also, can you share your docker-compose or docker run command?

**Comment by bergziege** [comment]
![image](https://user-images.githubusercontent.com/354288/172706607-de322d8b-89a8-4614-9587-52a9eb7aa300.png)
Also tried it with Adblock and Ghostery turned off ... no change.

```
version: "2.1"
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
    ports:
      - 7100:80
      - 7143:443
    restart: unless-stopped
```
Latest ngix log (from the config mount):

```
192.168.2.31 - - [08/Jun/2022:16:02:28 -0400] "GET /api/ping HTTP/1.1" 404 143 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0"```

The only thing that appears running is adding accounts and adding transactions into accounts. So its not totaly dead ;-)
