### ISSUE TITLE
Account transaction not showing up in envelope

### ISSUE THREAD

**Issue by bergziege** [linuxserver/budge#28]
Hi, I am running 0.0.8 via Docker and I am not be able to see that a trasaction has any influence on my envelope.

- Created a envelope "A"
- Created a transaction "-50" for "A" for 6/6/2022 (or any other month)
- Cleared the transaction
- Viewing envelopes
- The Transaction does not show up (no matter what month I select)

Expected:
- Envelope "A" should show "-50" as activity

Settings changed from default: Currency set to EUR
Browser: Edge and Firefox
Running via Docker:

```
version: "2.1"
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    ports:
      - 7080:80
      - 7443:443
    restart: unless-stopped
```
