### ISSUE TITLE
Create Account button doesn't work

### ISSUE THREAD

**Issue by engemil** [linuxserver/BudgE#38]
Im running the "budge"-container on an Ubuntu Server, with Docker.

I'm using the recommended docker compose file, where I adjusted the volumes folder for host side, and the ports for host side:

```
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/budge:/config
    ports:
      - 88:80
      - 444:443
    restart: unless-stopped
```
  
  I open the interface both with firefox and with google chrome, (https://serverip:444), and nothing happens when I press the "create account"-button
